name: Deploy to ninie-io

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ninie-io
          heroku_email: "mottet.lionel@gmail.com"
          buildpack: "https://github.com/heroku/heroku-buildpack-java.git"
        env:
          HD_BOT_TOKEN : ${{secrets.BOT_TOKEN}}
          HD_BOT_PREFIX: p