name: Deploy to test-ninie-io

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: test-ninie-io
            heroku_email: "mottet.lionel@gmail.com"
            buildpack: "https://github.com/heroku/heroku-buildpack-java.git"
        env:
          HD_BOT_TOKEN : ${{secrets.TEST_BOT_TOKEN}}
          HD_BOT_PREFIX: pt
  push:
    if: ${{ github.ref == 'develop' }}
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge develop -> master
        uses: devmsx/merge-branch@v1.3.1
        with:
          type: now
          target branch: main
          github_token: ${{ github.token }}